name: Lighthouse Mobile Config

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  push:
    branches:
      - master
  schedule:
    - cron: '*/180 * * * *'
  repository_dispatch:
    types: lighthouse

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Lighthouse on urls and validate with lighthouserc
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://nextjs-lighthouse-ci.golfthanakorn.now.sh/
          runs: 1
          configPath: '.github/lighthouse/custom-config/lighthouserc-mobile-config.json'
          uploadArtifacts: true